import { __renderWithLifecycle } from "./lifecycle";
import { isReactiveBinding, useReactiveEffect, type ReactiveBinding } from "./reactive";

type Primitive = string | number | boolean | null | undefined;
export type JSXChild = Node | Primitive | ReactiveBinding<any> | JSXChild[];

type Props = {
  children?: JSXChild;
  [key: string]: unknown;
};

type Component = (props: Props) => Node;
type StyleObject = Partial<CSSStyleDeclaration>;
type DatasetValue = string | number | boolean | null | undefined;
type RefCallback<T extends HTMLElement = HTMLElement> = (el: T) => void;
type RefObject<T extends HTMLElement = HTMLElement> = { current: T | null };

export const Fragment = Symbol("Fragment");
export type ElementType = string | typeof Fragment | Component;

declare global {
  namespace JSX {
    interface IntrinsicElements {
      [elemName: string]: Record<string, unknown>;
    }
    interface Element extends Node {}
  }
}

// Helper to remove any previous nodes generated by an inline dynamic expression slot
function clearDynamicNodes(startAnchor: Comment, endAnchor: Comment): void {
  const parent = startAnchor.parentNode;
  if (!parent) return;
  let current = startAnchor.nextSibling;
  while (current && current !== endAnchor) {
    const next = current.nextSibling;
    parent.removeChild(current);
    current = next;
  }
}

// Appends dynamic reactive children into DOM fragments or container bodies
function appendReactiveChild(parent: Node, binding: ReactiveBinding<any>): void {
  const startAnchor = document.createComment("reactive-start");
  const endAnchor = document.createComment("reactive-end");

  parent.appendChild(startAnchor);
  parent.appendChild(endAnchor);

  useReactiveEffect((...computedValues) => {
    const freshValue = binding.compute(...computedValues);

    // Clear out whatever old node layouts were rendered in the previous microtask loop
    clearDynamicNodes(startAnchor, endAnchor);

    if (freshValue === null || freshValue === undefined || typeof freshValue === "boolean") return;

    // Build temporary holding fragment to structure nested variables or text safely
    const tempFragment = document.createDocumentFragment();
    appendChild(tempFragment, freshValue);

    // Insert new elements right before our ending anchor tracking flag
    endAnchor.parentNode?.insertBefore(tempFragment, endAnchor);
  }, binding.deps as any);
}

export function appendChild(parent: Node, child: JSXChild): void {
  if (child === null || child === undefined || typeof child === "boolean") return;

  if (isReactiveBinding(child)) {
    appendReactiveChild(parent, child);
    return;
  }

  if (Array.isArray(child)) {
    for (const nested of child) appendChild(parent, nested);
    return;
  }

  if (child instanceof Node) {
    parent.appendChild(child);
    return;
  }
  parent.appendChild(document.createTextNode(String(child)));
}

const DOM_PROP_MAP: Record<string, string> = {
  class: "className",
  classname: "className",
  htmlfor: "htmlFor",
  readonly: "readOnly",
  autofocus: "autoFocus",
  autocomplete: "autoComplete",
  maxlength: "maxLength",
  minlength: "minLength",
  tabindex: "tabIndex"
};

const LIVE_PROPERTIES = new Set(["value", "checked", "disabled", "muted", "selected"]);

function setProp(el: HTMLElement, key: string, value: unknown): void {
  // Intercept reactive bindings bound to properties
  if (isReactiveBinding(value)) {
    useReactiveEffect((...values) => setProp(el, key, value.compute(...values)), value.deps as any);
    return;
  }

  // Normalize casing mismatches
  const lookupKey = key.toLowerCase();
  const normalizedKey = Object.prototype.hasOwnProperty.call(DOM_PROP_MAP, lookupKey)
    ? DOM_PROP_MAP[lookupKey]
    : key;

  // Inline Styles
  if (normalizedKey === "style") {
    if (typeof value === "string") {
      el.setAttribute("style", value);
    } else if (value && typeof value === "object") {
      el.removeAttribute("style");
      Object.assign(el.style, value as StyleObject);
    } else {
      el.removeAttribute("style");
    }
    return;
  }

  // Datasets (Object syntax style: dataset={{ id: 1 }})
  if (normalizedKey === "dataset" && value && typeof value === "object") {
    for (const [dKey, dVal] of Object.entries(value as Record<string, DatasetValue>)) {
      if (dVal === null || dVal === undefined) delete el.dataset[dKey];
      else el.dataset[dKey] = String(dVal);
    }
    return;
  }

  // Element References
  if (normalizedKey === "ref") {
    if (typeof value === "function") (value as RefCallback)(el);
    else if (value && typeof value === "object" && "current" in value) {
      (value as RefObject).current = el;
    }
    return;
  }

  // Safe Event Handlers
  if (normalizedKey.startsWith("on") && normalizedKey.length > 2) {
    const eventName = normalizedKey.slice(2).toLowerCase();
    (el as any)[`on${eventName}`] = typeof value === "function" ? value : null;
    return;
  }

  // Map normalized JS property names back to their standard HTML attribute matches
  const attrName =
    normalizedKey === "className" ? "class" : normalizedKey === "htmlFor" ? "for" : normalizedKey;

  // Clean Falsy State Clearing
  if (value === false || value === null || value === undefined || value === "") {
    if (LIVE_PROPERTIES.has(normalizedKey) && normalizedKey in el) {
      if (normalizedKey === "value") (el as any)[normalizedKey] = "";
      else (el as any)[normalizedKey] = false;
    }
    el.removeAttribute(attrName);
    return;
  }

  // Live JavaScript DOM Properties vs HTML Attributes
  if (LIVE_PROPERTIES.has(normalizedKey) && normalizedKey in el) {
    (el as any)[normalizedKey] = value === true ? true : value;
    return;
  }

  // Attribute Safe Guard Fallback (Handles data-*, aria-*, and custom keys)
  el.setAttribute(attrName, value === true ? "" : String(value));
}

const SVG_ELEMENTS = new Set([
  "svg",
  "path",
  "circle",
  "ellipse",
  "line",
  "rect",
  "polygon",
  "polyline",
  "g",
  "text",
  "tspan",
  "defs",
  "use",
  "symbol",
  "marker",
  "lineargradient",
  "radialgradient",
  "stop",
  "clippath",
  "mask",
  "image",
  "foreignobject"
]);

function createNode(type: ElementType, props: Props, key?: unknown): Node {
  // If it's a functional component, inject key back to props so the developer can access it
  if (typeof type === "function") {
    if (key !== undefined) {
      props = { ...props, key };
    }
    return __renderWithLifecycle(() => type(props));
  }

  if (type === Fragment) {
    const fragment = document.createDocumentFragment();
    if (props.children !== undefined) {
      appendChild(fragment, props.children);
    }
    return fragment;
  }

  let el: Element;
  const tagType = typeof type === "string" ? type.toLowerCase() : "";

  if (SVG_ELEMENTS.has(tagType)) {
    let svgTag = tagType;
    if (tagType === "lineargradient") svgTag = "linearGradient";
    else if (tagType === "radialgradient") svgTag = "radialGradient";
    else if (tagType === "clippath") svgTag = "clipPath";
    else if (tagType === "foreignobject") svgTag = "foreignObject";

    el = document.createElementNS("http://www.w3.org/2000/svg", svgTag);
  } else {
    el = document.createElement(type as string);
  }

  // Map incoming standard props
  for (const [propKey, value] of Object.entries(props)) {
    if (propKey === "children") continue;
    setProp(el as HTMLElement, propKey, value);
  }

  if (props.children !== undefined) {
    appendChild(el, props.children);
  }

  return el;
}

export function jsx(type: ElementType, props: Props, key?: unknown): Node {
  return createNode(type, props ?? {}, key);
}

export function jsxs(type: ElementType, props: Props, key?: unknown): Node {
  return createNode(type, props ?? {}, key);
}

export function jsxDEV(type: ElementType, props: Props, key?: unknown): Node {
  return createNode(type, props ?? {}, key);
}
